# Generated by Django 6.0.1 on 2026-09-24 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='intakes/')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=8)),
                ('precinct', models.CharField(blank=True, max_length=64)),
                ('engine', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('no_face', 'No Face'), ('no_match', 'No Match'), ('ambiguous', 'Ambiguous'), ('no_record', 'No Record'), ('profiled', 'Profiled')], default='received', max_length=16)),
                ('faces_detected', models.PositiveIntegerField(default=0)),
                ('match_score', models.FloatField(blank=True, null=True)),
                ('runner_up_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convicted', models.BooleanField(default=False)),
                ('sentence_kind', models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine'), ('community_service', 'Community Service'), ('probation', 'Probation'), ('imprisonment', 'Imprisonment')], max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('months', models.PositiveIntegerField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('review_profile', 'Can validate or reject suspect profiles'), ('adjudicate', 'Can apply convictions and sentences')],
            },
        ),
        migrations.CreateModel(
            name='SuspectProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('needs_review', 'Needs Review'), ('rejected', 'Rejected'), ('adjudicated', 'Adjudicated')], max_length=16)),
                ('snapshot', models.JSONField(help_text='Record summary at the time the profile was built')),
                ('checks', models.JSONField(help_text='Automated validation checks and their results')),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('target', models.CharField(max_length=128)),
                ('detail', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
