# Generated by Django 6.0.1 on 2026-09-24 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='matched_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.person'),
        ),
        migrations.AddField(
            model_name='intake',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgment',
            name='decided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgment',
            name='infraction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judgment', to='registry.infraction'),
        ),
        migrations.AddField(
            model_name='suspectprofile',
            name='intake',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='cases.intake'),
        ),
        migrations.AddField(
            model_name='suspectprofile',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='registry.person'),
        ),
        migrations.AddField(
            model_name='suspectprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to='cases.suspectprofile'),
        ),
    ]
