# Generated by Django 6.0.1 on 2026-09-24 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
        ('registry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intake',
            name='match_score',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='matched_person',
        ),
        migrations.RemoveField(
            model_name='intake',
            name='runner_up_score',
        ),
        migrations.AddField(
            model_name='intake',
            name='annotated',
            field=models.FileField(blank=True, help_text='Media with face boxes drawn', upload_to='intakes/annotated/'),
        ),
        migrations.AddField(
            model_name='intake',
            name='match_threshold',
            field=models.FloatField(blank=True, help_text='Cosine similarity needed to accept a match', null=True),
        ),
        migrations.AlterField(
            model_name='suspectprofile',
            name='intake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='cases.intake'),
        ),
        migrations.CreateModel(
            name='FaceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(help_text='Number shown on the annotated image (1-based)')),
                ('frame_index', models.PositiveIntegerField(default=0)),
                ('box_x', models.IntegerField(blank=True, null=True)),
                ('box_y', models.IntegerField(blank=True, null=True)),
                ('box_w', models.IntegerField(blank=True, null=True)),
                ('box_h', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('ambiguous', 'Ambiguous'), ('no_match', 'No Match')], max_length=16)),
                ('score', models.FloatField(blank=True, null=True)),
                ('runner_up_score', models.FloatField(blank=True, null=True)),
                ('support', models.PositiveIntegerField(default=1, help_text='Frames the identity was seen in (video)')),
                ('candidates', models.JSONField(default=list, help_text='Closest enrolled people: [{person_id, name, score}]')),
                ('candidate', models.ForeignKey(blank=True, help_text='Closest enrolled person, accepted or not', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='registry.person')),
                ('intake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='cases.intake')),
                ('person', models.ForeignKey(blank=True, help_text='Accepted identity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_matches', to='registry.person')),
            ],
            options={
                'ordering': ['intake_id', 'index'],
            },
        ),
        migrations.AddField(
            model_name='suspectprofile',
            name='face_match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='cases.facematch'),
        ),
        migrations.AddConstraint(
            model_name='suspectprofile',
            constraint=models.UniqueConstraint(fields=('intake', 'person'), name='one_profile_per_person_per_intake'),
        ),
        migrations.AddConstraint(
            model_name='facematch',
            constraint=models.UniqueConstraint(fields=('intake', 'index'), name='one_face_number_per_intake'),
        ),
    ]
