# Generated by Django 6.0.1 on 2026-09-25 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_per_face_matches'),
        ('registry', '0006_infraction_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='captured_at',
            field=models.DateTimeField(blank=True, help_text='When the photo or video was taken (not when it was submitted)', null=True),
        ),
        migrations.AddField(
            model_name='intake',
            name='latitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='intake',
            name='location',
            field=models.CharField(blank=True, help_text='Place or address where it was captured', max_length=255),
        ),
        migrations.AddField(
            model_name='intake',
            name='longitude',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='intake',
            name='related_occurrences',
            field=models.ManyToManyField(blank=True, help_text='Every occurrence on record for the individuals identified in this intake', related_name='intakes', to='registry.infraction'),
        ),
    ]
