# Generated by Django 6.0.1 on 2026-09-25 18:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_backfill_intake_capture_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='captured_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the photo or video was taken (not when it was submitted)'),
        ),
    ]
