# Generated by Django 6.0.1 on 2026-09-24 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Infraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('traffic', 'Traffic'), ('vandalism', 'Vandalism'), ('theft', 'Theft'), ('fraud', 'Fraud'), ('drugs', 'Drugs'), ('burglary', 'Burglary'), ('assault', 'Assault'), ('robbery', 'Robbery')], max_length=32)),
                ('severity', models.PositiveSmallIntegerField(help_text='1 (minor) to 5 (grave)')),
                ('description', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('precinct', models.CharField(blank=True, max_length=64)),
                ('convicted', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=16)),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('warning', 'Warning'), ('fine', 'Fine'), ('community_service', 'Community Service'), ('probation', 'Probation'), ('imprisonment', 'Imprisonment')], max_length=32)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hours', models.PositiveIntegerField(blank=True, null=True)),
                ('months', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('defaulted', 'Defaulted')], default='pending', max_length=16)),
                ('imposed_at', models.DateTimeField()),
                ('infraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='registry.infraction')),
                ('judgment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to='cases.judgment')),
            ],
            options={
                'verbose_name_plural': 'penalties',
                'ordering': ['imposed_at'],
            },
        ),
        migrations.AddField(
            model_name='infraction',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infractions', to='registry.person'),
        ),
        migrations.CreateModel(
            name='FaceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=64)),
                ('embedding', models.JSONField()),
                ('source', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='registry.person')),
            ],
        ),
        migrations.AddConstraint(
            model_name='infraction',
            constraint=models.CheckConstraint(condition=models.Q(('severity__gte', 1), ('severity__lte', 5)), name='infraction_severity_1_5'),
        ),
    ]
