# Generated by Django 6.0.1 on 2026-09-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_facetemplate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infraction',
            name='location',
            field=models.CharField(blank=True, help_text='Place or address where it happened', max_length=255),
        ),
    ]
