"""
Django settings for redqueen project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-hqnbr6l8ftx4v4p0cne_5#_lb10_4uj^*p92fk5xd1v-km(l+z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'registry',
    'vision',
    'cases',
    'precog',
    'api',
    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'redqueen.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'redqueen.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Media uploads (photos / videos submitted to the system)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
}

# RedQueen pipeline configuration
REDQUEEN = {
    # "opencv-sface" (YuNet detector + SFace embeddings) or "synthetic" (test double
    # used with the generated dummy portraits; never use it on real people).
    'VISION_ENGINE': os.environ.get('REDQUEEN_VISION_ENGINE', 'opencv-sface'),
    'MODEL_DIR': BASE_DIR / 'models',
    # None = use the engine's default. Thresholds are engine specific and must be
    # calibrated on your own data before any real-world use.
    'MATCH_THRESHOLD': None,
    # Best candidate must beat the runner-up by this much, otherwise the match is ambiguous.
    'MATCH_MARGIN': 0.05,
    # Extra similarity above the threshold required before a profile auto-validates.
    'AUTO_VALIDATE_EXTRA': 0.10,
    # Video handling: analyse every Nth frame, at most MAX_FRAMES frames, and require
    # the same person in at least MIN_SUPPORT frames.
    'VIDEO_FRAME_STRIDE': 10,
    'VIDEO_MAX_FRAMES': 60,
    'VIDEO_MIN_SUPPORT': 2,
    # Larger images/frames are shrunk to this many pixels on the long side before detection.
    'MAX_IMAGE_SIDE': 1920,
}

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
# Uploaded faces are personal data: served only through authenticated views, never publicly.
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024

SWAGGER_SETTINGS = {'USE_SESSION_AUTH': True}
SWAGGER_USE_COMPAT_RENDERERS = False
