# Generated by Django 6.0.1 on 2026-09-24 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('level', models.CharField(max_length=16)),
                ('trajectory', models.CharField(max_length=16)),
                ('expected_severity', models.FloatField()),
                ('votes', models.JSONField()),
                ('minority_report', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='registry.person')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
